import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("builder UI prototype includes palette, canvas, props, preview, and save controls", async () => {
  const html = await readFile(new URL("../packages/builder-ui/app/index.html", import.meta.url), "utf8");
  const script = await readFile(new URL("../packages/builder-ui/app/builder.js", import.meta.url), "utf8");

  assert.match(html, /data-block-palette/);
  assert.match(html, /data-canvas/);
  assert.match(html, /data-props-panel/);
  assert.match(html, /data-preview/);
  assert.match(html, /data-save-layout/);
  assert.match(script, /commerce\/product-price/);
  assert.match(script, /site\/logo/);
  assert.match(script, /site\/nav/);
  assert.match(script, /site\/dark-mode-toggle/);
  assert.match(script, /URL\.createObjectURL/);
});

test("basic shop exposes builder demo in public assets", async () => {
  const html = await readFile(new URL("../examples/basic-shop/public/builder.html", import.meta.url), "utf8");
  const script = await readFile(new URL("../examples/basic-shop/public/builder-ui/builder.js", import.meta.url), "utf8");

  assert.match(html, /\/builder-ui\/builder.css/);
  assert.match(html, /\/builder-ui\/builder.js/);
  assert.match(html, /data-route-context/);
  assert.match(html, /data-route-meta/);
  assert.match(html, /data-draft-status/);
  assert.match(html, /data-export-layout/);
  assert.match(html, /data-reset-layout/);
  assert.match(html, /data-apply-header-demo/);
  assert.match(html, /data-build-route-preview/);
  assert.doesNotMatch(html, /data-canvas/);
  assert.doesNotMatch(html, /builder-canvas-wrap/);
  assert.match(html, /Live Preview/);
  assert.match(script, /new URLSearchParams\(window\.location\.search\)/);
  assert.match(script, /\/data\/routes\/\$\{slug \|\| "index"\}\.json/);
  assert.match(script, /runtime\?\.fragmentUrl/);
  assert.match(script, /\/data\/templates\/manifest\.json/);
  assert.match(script, /function loadTemplateForRoute/);
  assert.match(script, /function ensureEditableLayout/);
  assert.doesNotMatch(script, /class="route-preview"/);
  assert.match(script, /wpsc_builder_route_draft:/);
  assert.match(script, /layout\/row/);
  assert.match(script, /data-drop-column-id/);
  assert.match(script, /function createRowNode/);
  assert.match(script, /function setRowColumnCount/);
  assert.match(script, /function removeNode/);
  assert.match(script, /function moveNode/);
  assert.match(script, /STYLE_SETTINGS/);
  assert.match(script, /function renderStyleFields/);
  assert.match(script, /contentMaxWidth/);
  assert.match(script, /builder-row-shell/);
  assert.match(script, /function takeNode/);
  assert.match(script, /function insertNode/);
  assert.match(script, /function findDropTarget/);
  assert.match(script, /application\/x-wpsc-node-id/);
  assert.match(script, /nodeId: event\.dataTransfer\.getData/);
  assert.match(script, /targetNodeId/);
  assert.match(script, /is-drop-before/);
  assert.match(script, /is-drop-after/);
  assert.match(script, /function openBuiltRoutePreview/);
  assert.doesNotMatch(script, /data-selected-action/);
  assert.doesNotMatch(script, /selected-node-actions/);
  assert.doesNotMatch(script, /addBlock\(blockButton\.dataset\.addBlock\)/);
  assert.match(script, /site\/logo/);
  assert.match(script, /site\/nav/);
  assert.match(script, /site\/dark-mode-toggle/);
  assert.match(script, /site\/header/);
  assert.match(script, /draggable="true"/);
  assert.match(script, /wpsc-builder-drop/);
  assert.match(script, /wpsc-builder-select/);
  assert.match(script, /wpsc-builder-remove/);
  assert.match(script, /data-remove-node-id/);
  assert.match(script, /builder-preview-remove/);
  assert.match(script, /builder-preview-node\.is-selected\[data-node-id\]/);
  assert.match(script, /propsPanel\.addEventListener\("input"[\s\S]*markDraftDirty\(\);\n  renderCanvas\(\);\n  renderPreview\(\);\n  renderDraftStatus\(\);/);
  assert.match(script, /function renderSelectablePreviewNode/);
  assert.match(script, /data-header-action="add-row"/);
  assert.match(script, /data-header-action="add-column"/);
  assert.match(script, /data-child-block="site\/logo"/);
  assert.match(script, /wpsc-site-header__row/);
  assert.match(script, /function normalizeHref/);
  assert.match(script, /function parseNavItems/);
  assert.match(script, /Mỗi dòng: Nhãn \| \/duong-dan/);
  assert.match(script, /function createDraftKey/);
  assert.match(script, /function loadDraft/);
  assert.match(script, /function saveDraft/);
  assert.match(script, /function applyHeaderDemo/);
  assert.match(script, /localStorage\.setItem/);
  assert.match(script, /sanitizePreviewHtml/);
  assert.match(script, /<div class="content-text">/);
  assert.match(script, /resolveContentText/);
  assert.match(script, /createArchiveLinks/);
  assert.doesNotMatch(script, /19900000/);
  assert.doesNotMatch(script, /href="\/dien-thoai">Điện thoại/);
});
