import assert from "node:assert/strict";
import { access, mkdtemp, mkdir, readlink, rm, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import createCoreUpdateActivationService from "../framework/src/product/update/createCoreUpdateActivationService.js";

test("Core Update activation atomically switches active symlink and preserves both releases", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "wpsc-active-")); try { await mkdir(path.join(root, "core/releases/1.0.0"), { recursive: true }); await mkdir(path.join(root, "core/releases/1.1.0"), { recursive: true }); await writeFile(path.join(root, "core/releases/1.1.0/.wpsc-staged.json"), '{"version":"1.1.0"}'); await symlink("releases/1.0.0", path.join(root, "core/active")); const result = await createCoreUpdateActivationService({ workspaceDir: root }).activate("1.1.0"); assert.equal(result.previousPointer, "releases/1.0.0"); assert.equal(await readlink(path.join(root, "core/active")), "releases/1.1.0"); await mkdir(path.join(root, "core/releases/1.0.0"), { recursive: true }); } finally { await rm(root, { force: true, recursive: true }); } });

test("C035 failure before atomic rename preserves old active symlink", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "wpsc-active-fail-")); try { await mkdir(path.join(root, "core/releases/1.0.0"), { recursive: true }); await mkdir(path.join(root, "core/releases/1.1.0"), { recursive: true }); await writeFile(path.join(root, "core/releases/1.1.0/.wpsc-staged.json"), '{"version":"1.1.0"}'); await symlink("releases/1.0.0", path.join(root, "core/active")); const service = createCoreUpdateActivationService({ renamePointer: async () => { throw new Error("before rename"); }, workspaceDir: root }); await assert.rejects(service.activate("1.1.0"), /before rename/); assert.equal(await readlink(path.join(root, "core/active")), "releases/1.0.0"); await access(path.join(root, "core/releases/1.0.0")); await access(path.join(root, "core/releases/1.1.0")); } finally { await rm(root, { force: true, recursive: true }); } });

test("C035 rejects missing or invalid staged releases without pointer mutation", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "wpsc-active-invalid-")); try { await mkdir(path.join(root, "core/releases/1.1.0"), { recursive: true }); await mkdir(path.join(root, "core"), { recursive: true }); await symlink("releases/1.0.0", path.join(root, "core/active")); const service = createCoreUpdateActivationService({ workspaceDir: root }); assert.equal((await service.activate("1.2.0")).ok, false); assert.equal((await service.activate("1.1.0")).ok, false); assert.equal(await readlink(path.join(root, "core/active")), "releases/1.0.0"); } finally { await rm(root, { force: true, recursive: true }); } });

test("C035 restart ignores an interrupted temporary pointer and keeps active authoritative", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "wpsc-active-restart-")); try { await mkdir(path.join(root, "core"), { recursive: true }); await symlink("releases/1.0.0", path.join(root, "core/active")); await symlink("releases/1.1.0", path.join(root, "core/active.interrupted.tmp")); createCoreUpdateActivationService({ workspaceDir: root }); assert.equal(await readlink(path.join(root, "core/active")), "releases/1.0.0"); assert.equal(await readlink(path.join(root, "core/active.interrupted.tmp")), "releases/1.1.0"); } finally { await rm(root, { force: true, recursive: true }); } });
