import assert from "node:assert/strict";
import { mkdtemp, mkdir, readlink, rm, symlink } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import createCoreUpdateRecoveryService from "../framework/src/product/update/createCoreUpdateRecoveryService.js";
import createCoreUpdateHealthService, { CoreUpdateHealthState } from "../framework/src/product/update/createCoreUpdateHealthService.js";

const healthyChecks = () => Object.fromEntries(["runtime", "scheduler", "queue", "dispatcher", "buildIntegration"].map((name) => [name, async () => ({ ok: true })]));

test("C036 keeps a healthy activated release active and completes every health contract", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "wpsc-health-ok-")); try { await mkdir(path.join(root, "core"), { recursive: true }); await symlink("releases/1.1.0", path.join(root, "core/active")); const result = await createCoreUpdateHealthService({ checks: healthyChecks(), recovery: { restore: async () => { throw new Error("must not rollback"); } }, workspaceDir: root }).verify({ recoveryId: "before" }); assert.equal(result.state, CoreUpdateHealthState.COMPLETED); assert.equal(result.results.length, 5); assert.equal(await readlink(path.join(root, "core/active")), "releases/1.1.0"); } finally { await rm(root, { force: true, recursive: true }); } });

test("C036 health failure restores the C032 recovery point and is repeat-safe", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "wpsc-health-rollback-")); try { await mkdir(path.join(root, "core/releases/1.0.0"), { recursive: true }); await mkdir(path.join(root, "core/releases/1.1.0"), { recursive: true }); await symlink("releases/1.0.0", path.join(root, "core/active")); const recovery = createCoreUpdateRecoveryService({ workspaceDir: root }); await recovery.create({ recoveryId: "before" }); await rm(path.join(root, "core/active")); await symlink("releases/1.1.0", path.join(root, "core/active")); let restores = 0; const wrapped = { restore: async (id) => { restores += 1; return recovery.restore(id); } }; const checks = healthyChecks(); checks.scheduler = async () => ({ ok: false }); const service = createCoreUpdateHealthService({ checks, recovery: wrapped, workspaceDir: root }); const first = await service.verify({ recoveryId: "before" }); assert.equal(first.state, CoreUpdateHealthState.ROLLED_BACK, JSON.stringify(first)); assert.equal((await service.verify({ recoveryId: "before" })).state, CoreUpdateHealthState.ROLLED_BACK); assert.equal(restores, 1); } finally { await rm(root, { force: true, recursive: true }); } });

test("C036 records RECOVERY_REQUIRED when automatic rollback fails", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "wpsc-health-fail-")); try { const checks = healthyChecks(); checks.runtime = async () => { throw new Error("startup failed"); }; const result = await createCoreUpdateHealthService({ checks, recovery: { restore: async () => { throw new Error("restore failed"); } }, workspaceDir: root }).verify({ recoveryId: "before" }); assert.equal(result.ok, false); assert.equal(result.state, CoreUpdateHealthState.RECOVERY_REQUIRED); } finally { await rm(root, { force: true, recursive: true }); } });

test("C036 resumes a persisted ROLLBACK state after restart", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "wpsc-health-resume-")); try { await mkdir(path.join(root, "storage/updates"), { recursive: true }); await (await import("node:fs/promises")).writeFile(path.join(root, "storage/updates/health.json"), JSON.stringify({ recoveryId: "before", results: [{ name: "queue", ok: false }], state: "ROLLBACK" })); const restarted = createCoreUpdateHealthService({ checks: healthyChecks(), recovery: { restore: async () => ({ ok: true }) }, workspaceDir: root }); assert.equal((await restarted.resume()).state, CoreUpdateHealthState.ROLLED_BACK); } finally { await rm(root, { force: true, recursive: true }); } });
