import escapeHtml from "../shared/escapeHtml.js";
import { randomUUID } from "node:crypto";

export const RUNTIME_BROWSER_VIEWS_VERSION = "1.0";

function document(title, body, script) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><style>:root{--ink:#172b25;--moss:#476653;--lime:#d7e678;--paper:#f8f4eb;--coral:#e9684a;--line:#c8d0c0}*{box-sizing:border-box}body{min-height:100vh;margin:0;color:var(--ink);background:radial-gradient(circle at 12% 5%,#d7e678 0 2%,transparent 18%),radial-gradient(circle at 90% 92%,#f1b29a 0 1%,transparent 20%),#e9ede4;font:16px/1.5 Georgia,serif}main{width:min(100% - 2rem,58rem);margin:clamp(2rem,8vh,7rem) auto;padding:clamp(1.5rem,5vw,4.5rem);background:rgba(248,244,235,.92);border:1px solid var(--line);box-shadow:16px 16px 0 var(--ink)}.eyebrow{margin:0 0 1rem;color:var(--moss);font:700 .7rem/1 ui-monospace,SFMono-Regular,monospace;letter-spacing:.16em;text-transform:uppercase}.kicker{max-width:38rem;margin:.8rem 0 2.4rem;color:#56675d;font-size:1.1rem}h1{max-width:12ch;margin:0;font-size:clamp(2.8rem,9vw,6rem);line-height:.92;letter-spacing:-.065em}h2{margin:0;font-size:1rem;font-family:ui-monospace,SFMono-Regular,monospace;letter-spacing:.08em;text-transform:uppercase}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;margin:2rem 0}.tile{padding:1.15rem;border:1px solid var(--line);background:#fffdf7}.tile strong{display:block;margin-top:.35rem;font-size:1.15rem}form{margin-top:2rem;padding:1.4rem;background:#172b25;color:#f8f4eb}label{display:grid;gap:.4rem;margin:1rem 0;font:700 .76rem/1 ui-monospace,SFMono-Regular,monospace;letter-spacing:.08em;text-transform:uppercase}input{width:100%;padding:.85rem;border:1px solid #829685;background:#f8f4eb;color:var(--ink);font:1rem Georgia,serif}button{padding:.85rem 1.1rem;border:1px solid var(--lime);background:var(--lime);color:var(--ink);font:700 .78rem/1 ui-monospace,SFMono-Regular,monospace;letter-spacing:.08em;text-transform:uppercase;cursor:pointer;transition:transform .16s ease,background .16s ease}button:hover{transform:translate(-2px,-2px);background:#e7f68e}button+button{margin-left:.5rem;background:transparent;color:var(--paper);border-color:var(--lime)}.actions{margin:2rem 0}.actions button+button{background:#fffdf7;color:var(--ink);border-color:var(--ink)}.status{min-height:4rem;margin:1.5rem 0 0;padding:1rem;border-left:4px solid var(--coral);background:#fffdf7;color:#384b40;white-space:pre-wrap;font:12px/1.5 ui-monospace,SFMono-Regular,monospace}@media(max-width:600px){main{box-shadow:8px 8px 0 var(--ink)}.grid{grid-template-columns:1fr}h1{font-size:3.3rem}button{width:100%;margin-top:.5rem}button+button{margin-left:0}}</style></head><body>${body}<script>${script}</script></body></html>`;
}

const installerScript = `const out=document.querySelector('[data-status]');
function show(value){out.textContent=typeof value==='string'?value:JSON.stringify(value,null,2)}
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body||{})});const data=await r.json();if(!data.ok)show(data.diagnostics);return data}
document.querySelector('[data-install]').addEventListener('submit',async(event)=>{event.preventDefault();const config=Object.fromEntries(new FormData(event.currentTarget));const start=await api('/installer/start');if(!start.ok)return;const complete=await api('/installer/complete',{configuration:config,sessionId:start.session.id});if(complete.ok)location.reload();});`;

const dashboardScript = `const out=document.querySelector('[data-status]');
function show(value){out.textContent=typeof value==='string'?value:JSON.stringify(value,null,2)}
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body||{})});const data=await r.json();show(data);if(data.ok&&path==='/dashboard/build')location.reload();return data}
function sourcePayload(form){const credentials={};for(const key of ['applicationPassword','woocommerceConsumerKey','woocommerceConsumerSecret']){const input=form.elements[key];if(input.value&&!input.value.startsWith('wpsc_mask_'))credentials[key]=input.value}const username=form.elements.wordpressUsername;if(username.value!==username.defaultValue)credentials.wordpressUsername=username.value;return{credentials,source:{endpoint:form.elements.endpoint.value,type:form.elements.sourceType.value}}}
document.querySelector('[data-source]').addEventListener('submit',(event)=>{event.preventDefault();api('/dashboard/source/register',sourcePayload(event.currentTarget))});
document.querySelector('[data-source-test]').addEventListener('click',()=>api('/dashboard/source/test',sourcePayload(document.querySelector('[data-source]'))));document.querySelector('[data-webhook]').addEventListener('click',()=>api('/dashboard/webhook/register'));
document.querySelector('[data-build]').addEventListener('click',()=>api('/dashboard/build'));`;

export default function createRuntimeBrowserViews() {
  return Object.freeze({
    dashboard(snapshot) {
      const name = escapeHtml(snapshot.metadata?.name || "WPSC Site");
      const state = escapeHtml(({ READY_FOR_FIRST_BUILD: "Ready for first build", RUNNING: "Website running", SETUP_REQUIRED: "Setup required" })[snapshot.metadata?.status] || snapshot.metadata?.status || "Unknown");
      const source = escapeHtml(snapshot.source?.connected ? snapshot.source.sourceType : "Not connected");
      const sourceType = escapeHtml(snapshot.source?.sourceType || "wordpress");
      const endpoint = escapeHtml(snapshot.source?.endpoint || "");
      const credentials = snapshot.credentials || {};
      const masked = (key) => credentials[key] ? `wpsc_mask_${randomUUID()}` : "";
      const username = escapeHtml(credentials.wordpressUsername || "");
      return document(`${name} Dashboard`, `<main data-wpsc-dashboard><p class="eyebrow">WPSC / Site Control Room</p><h1>${name}</h1><p class="kicker">Check the publishing source without changing your Site. Save source only after the connection passes; that is when Runtime persists the configuration.</p><section class="grid"><article class="tile"><h2>Runtime</h2><strong>${state}</strong></article><article class="tile"><h2>Source</h2><strong>${source}</strong></article></section><form data-source><h2>Connect a source</h2><label>Source type<input name="sourceType" required value="${sourceType}"></label><label>Source endpoint<input name="endpoint" required type="url" value="${endpoint}" placeholder="https://source.example"></label><label>WordPress username<input name="wordpressUsername" required autocomplete="username" value="${username}" placeholder="Not configured"></label><label>Application Password<input name="applicationPassword" required type="password" autocomplete="new-password" value="${masked("applicationPassword")}" placeholder="Not configured"></label><label>WooCommerce Consumer Key<input name="woocommerceConsumerKey" type="password" autocomplete="off" value="${masked("woocommerceConsumerKey")}" placeholder="Optional - enter to enable WooCommerce"></label><label>WooCommerce Consumer Secret<input name="woocommerceConsumerSecret" type="password" autocomplete="off" value="${masked("woocommerceConsumerSecret")}" placeholder="Optional - enter to enable WooCommerce"></label><button type="button" data-source-test>Check connection</button><button>Save source</button></form><div class="actions"><button data-webhook>Register webhook</button><button data-build>Run first build</button></div><pre class="status" data-status>Check the connection before saving source settings.</pre></main>`, dashboardScript);
    },
    installer(siteId) {
      return document("Install WPSC Site", `<main data-wpsc-installer><p class="eyebrow">WPSC / First Run</p><h1>Set up ${escapeHtml(siteId)}</h1><p class="kicker">This is the control plane for your static Site. Start with its identity; the dashboard will guide source connection, webhook registration, and the first build.</p><section class="grid"><article class="tile"><h2>01</h2><strong>Site identity</strong></article><article class="tile"><h2>02</h2><strong>Build-ready dashboard</strong></article></section><form data-install><h2>Site details</h2><label>Site name<input name="siteName" required value="${escapeHtml(siteId)}"></label><label>Locale<input name="locale" required value="vi-VN"></label><button>Enter dashboard</button></form><pre class="status" data-status>Ready to initialize this Site.</pre></main>`, installerScript);
    },
    version: RUNTIME_BROWSER_VIEWS_VERSION
  });
}
