import escapeHtml from "../../shared/escapeHtml.js";
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export const RUNTIME_BROWSER_VIEWS_VERSION = "2.0";
const stylesheet = readFileSync(fileURLToPath(new URL("./runtime-control.compiled.css", import.meta.url)), "utf8");

function document(title, body, script) {
  return `<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${escapeHtml(title)}</title><link rel="stylesheet" href="/_wpsc/runtime-control.css?v=2"><script>try{const t=localStorage.getItem('wpsc-theme');if(t)document.documentElement.dataset.theme=t}catch(e){}</script></head><body>${body}<script>${script}</script></body></html>`;
}

const sharedScript = `
const stack=document.querySelector('[data-notices]');
const themeButton=document.querySelector('[data-theme-toggle]');
function setTheme(theme){document.documentElement.dataset.theme=theme;try{localStorage.setItem('wpsc-theme',theme)}catch(e){}if(themeButton)themeButton.textContent=theme==='dark'?'☀ Light':'☾ Dark'}
if(themeButton){const current=document.documentElement.dataset.theme|| (matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');setTheme(current);themeButton.addEventListener('click',()=>setTheme((document.documentElement.dataset.theme||'light')==='dark'?'light':'dark'))}
function notice(type,title,message,action,handler){const item=document.createElement('div');item.className='notice '+type;const icon=document.createElement('span');icon.className='notice-icon';icon.textContent=({success:'✓',warning:'!',error:'×',info:'i'}[type]||'i');const content=document.createElement('div');const heading=document.createElement('strong');heading.textContent=title;const copy=document.createElement('p');copy.textContent=message;content.append(heading,copy);if(action){const button=document.createElement('button');button.className='secondary';button.textContent=action;button.onclick=handler;content.append(button)}item.append(icon,content);stack?.prepend(item)}
function friendly(data){const error=data?.diagnostics?.errors?.[0];if(!error)return null;const map={"source.registration.adapter.failed":["Không thể kết nối nguồn","Kiểm tra endpoint, username và Application Password rồi thử lại."],"wordpress.webhook.bridge.unavailable":["Webhook chưa sẵn sàng","Kiểm tra bridge plugin và địa chỉ callback của Site."],"runtime.installer.persistence.failed":["Chưa lưu được thông tin Site","Kiểm tra quyền ghi cấu hình rồi thử lại."],"build.integration.failed":["Build chưa hoàn tất","Nguồn dữ liệu hoặc nội dung trả về chưa hợp lệ. Hãy sửa phần được báo lỗi rồi thử lại."]};const text=map[error.code]||["Chưa hoàn tất thao tác",error.message||"Hãy kiểm tra lại thông tin và thử lại."];return {message:text[1],title:text[0]}}
async function api(path,body,button){if(button){button.disabled=true;button.dataset.label=button.textContent;button.textContent='Đang xử lý…'}try{const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body||{})});const data=await response.json();if(!data.ok){const f=friendly(data);notice('error',f?.title||'Không thể hoàn tất',f?.message||'Vui lòng thử lại.')}return data}catch(error){notice('error','Không kết nối được Runtime','Máy chủ đang bận hoặc tạm thời không phản hồi.')}finally{if(button){button.disabled=false;button.textContent=button.dataset.label}}}
`;

const installerScript = `${sharedScript}
const form=document.querySelector('[data-install]');form.addEventListener('submit',async(event)=>{event.preventDefault();const fields=Object.fromEntries(new FormData(form));let invalid=false;form.querySelectorAll('[required]').forEach(input=>{input.setAttribute('aria-invalid',String(!input.value.trim()));invalid ||= !input.value.trim()});if(invalid){notice('warning','Thiếu thông tin','Hãy điền đầy đủ các trường bắt buộc trước khi tiếp tục.');return}const start=await api('/installer/start',{},form.querySelector('button'));if(!start?.ok)return;const complete=await api('/installer/complete',{configuration:fields,sessionId:start.session.id},form.querySelector('button'));if(complete?.ok){notice('success','Đã khởi tạo Site','Đang chuyển sang Dashboard để kết nối nguồn dữ liệu.');setTimeout(()=>location.reload(),700)}});`;

const dashboardScript = `${sharedScript}
function sourcePayload(form){const credentials={};for(const key of ['applicationPassword','woocommerceConsumerKey','woocommerceConsumerSecret']){const input=form.elements[key];if(input.value&&!input.value.startsWith('wpsc_mask_'))credentials[key]=input.value}const username=form.elements.wordpressUsername;if(username.value!==username.defaultValue)credentials.wordpressUsername=username.value;return{credentials,source:{endpoint:form.elements.endpoint.value,type:form.elements.sourceType.value}}}
function validateSource(form){const endpoint=form.elements.endpoint,username=form.elements.wordpressUsername,password=form.elements.applicationPassword,key=form.elements.woocommerceConsumerKey,secret=form.elements.woocommerceConsumerSecret;const invalid=[];if(!endpoint.checkValidity())invalid.push(endpoint);if(!username.value.trim())invalid.push(username);if(!password.value.trim())invalid.push(password);if(Boolean(key.value.trim())!==Boolean(secret.value.trim())){invalid.push(key,secret);notice('warning','Thiếu thông tin WooCommerce','Consumer Key và Consumer Secret phải được nhập cùng nhau, hoặc để trống cả hai để dùng website blog.')}invalid.forEach(input=>input.setAttribute('aria-invalid','true'));if(invalid.length&&!key.matches('[aria-invalid="true"]'))notice('warning','Kiểm tra lại thông tin','Endpoint, Username và Application Password là bắt buộc để kết nối WordPress.');return invalid.length===0}
const sourceForm=document.querySelector('[data-source]');sourceForm.addEventListener('submit',async(event)=>{event.preventDefault();if(!validateSource(sourceForm))return;const button=event.submitter||sourceForm.querySelector('[data-save]');const result=await api('/dashboard/source/register',sourcePayload(sourceForm),button);if(result?.ok)notice('success','Đã lưu nguồn','Thông tin nguồn đã được lưu ở backend của Site.')});document.querySelector('[data-source-test]').addEventListener('click',async(event)=>{if(!validateSource(sourceForm))return;const result=await api('/dashboard/source/test',sourcePayload(sourceForm),event.currentTarget);if(result?.ok)notice('success','Kết nối thành công','WordPress đã sẵn sàng. WooCommerce là tuỳ chọn riêng.')});document.querySelector('[data-webhook]').addEventListener('click',async(event)=>{const result=await api('/dashboard/webhook/register',{},event.currentTarget);if(result?.ok)notice('success','Webhook đã đăng ký','Runtime sẽ nhận thay đổi từ WordPress.')});document.querySelector('[data-build]').addEventListener('click',async(event)=>{const result=await api('/dashboard/build',{},event.currentTarget);if(result?.ok){notice('success','Build thành công','Website đã được xuất bản.');setTimeout(()=>location.reload(),700)}});`;

function frame(name, eyebrow, heading, lead, body) { return `<div class="shell"><header class="topbar"><span class="brand">WPSC / ${escapeHtml(name)}</span><button class="theme-toggle" type="button" data-theme-toggle>☾ Dark</button></header><section class="hero"><p class="eyebrow">${eyebrow}</p><h1>${heading}</h1><p class="lead">${lead}</p>${body}<div class="notice-stack" data-notices aria-live="polite"></div></section></div>`; }

export default function createRuntimeBrowserViews() {
  return Object.freeze({
    dashboard(snapshot) {
      const name=escapeHtml(snapshot.metadata?.name||"WPSC Site"); const state=escapeHtml(({READY_FOR_FIRST_BUILD:"Sẵn sàng build",RUNNING:"Website đang chạy",SETUP_REQUIRED:"Cần thiết lập"})[snapshot.metadata?.status]||snapshot.metadata?.status||"Chưa xác định"); const source=escapeHtml(snapshot.source?.connected?snapshot.source.sourceType:"Chưa kết nối"); const sourceType=escapeHtml(snapshot.source?.sourceType||"wordpress"); const endpoint=escapeHtml(snapshot.source?.endpoint||""); const credentials=snapshot.credentials||{}; const masked=(key)=>credentials[key]?`wpsc_mask_${randomUUID()}`:""; const username=escapeHtml(credentials.wordpressUsername||"");
      const body=`<div class="steps"><div class="step active"><small>01</small><strong>Nguồn dữ liệu</strong></div><div class="step"><small>02</small><strong>Webhook</strong></div><div class="step"><small>03</small><strong>Kiểm tra</strong></div><div class="step"><small>04</small><strong>Xuất bản</strong></div></div><div class="summary"><div class="metric"><small>Runtime</small><strong>${state}</strong></div><div class="metric"><small>Source</small><strong>${source}</strong></div></div><form class="panel" data-source><h2>Kết nối WordPress</h2><p>Nhập thông tin nguồn. WooCommerce là tuỳ chọn; website blog không cần Consumer Key hoặc Consumer Secret.</p><div class="field-grid"><label>Loại nguồn<input name="sourceType" required value="${sourceType}"></label><label>Endpoint WordPress<input name="endpoint" required type="url" value="${endpoint}" placeholder="https://wordpress.example"></label><label>Username WordPress<input name="wordpressUsername" required autocomplete="username" value="${username}" placeholder="Username quản trị"></label><label>Application Password<input name="applicationPassword" required type="password" autocomplete="new-password" value="${masked("applicationPassword")}" placeholder="Nhập Application Password"></label></div><details class="optional"><summary>Tuỳ chọn WooCommerce</summary><div class="field-grid"><label>Consumer Key<small>Chỉ nhập nếu Site có bán hàng</small><input name="woocommerceConsumerKey" type="password" autocomplete="off" value="${masked("woocommerceConsumerKey")}" placeholder="ck_…"></label><label>Consumer Secret<small>Chỉ nhập nếu Site có bán hàng</small><input name="woocommerceConsumerSecret" type="password" autocomplete="off" value="${masked("woocommerceConsumerSecret")}" placeholder="cs_…"></label></div></details><div class="actions"><button type="button" data-source-test>Kiểm tra kết nối</button><button class="secondary" data-save>Lưu nguồn</button></div></form><div class="actions"><button type="button" data-webhook>Đăng ký Webhook</button><button type="button" class="secondary" data-build>Build website đầu tiên</button></div>`;
      return document(`${name} Dashboard`,frame(name,"WPSC / Control Room",name,"Thiết lập nguồn dữ liệu và xuất bản website theo từng bước. Mọi thông báo sẽ hiển thị ngay tại đây.",body),dashboardScript);
    },
    installer(siteId) { const safe=escapeHtml(siteId); const body=`<div class="steps"><div class="step active"><small>01</small><strong>Thông tin Site</strong></div><div class="step"><small>02</small><strong>Kết nối nguồn</strong></div><div class="step"><small>03</small><strong>Xuất bản</strong></div><div class="step"><small>04</small><strong>Website chạy</strong></div></div><form class="panel" data-install><h2>Bắt đầu với Site của bạn</h2><p>Chỉ mất một phút để khởi tạo. Bạn có thể kết nối WordPress ngay sau bước này.</p><div class="field-grid"><label>Tên Site<input name="siteName" required value="${safe}" placeholder="Tên website"></label><label>Ngôn ngữ<input name="locale" required value="vi-VN" placeholder="vi-VN"></label></div><div class="actions"><button>Tiếp tục thiết lập</button></div></form>`; return document("Thiết lập WPSC",frame("First Run","WPSC / First Run",`Chào mừng đến với ${safe}`,"Một không gian đơn giản để kết nối nội dung, kiểm tra nguồn và đưa website lên online.",body),installerScript); },
    stylesheet: () => stylesheet,
    version: RUNTIME_BROWSER_VIEWS_VERSION
  });
}
