import createRuntimeConfig from "../runtime/bootstrap/createRuntimeConfig.js";

export const INSTALLATION_CONFIG_GENERATOR_VERSION = "1.0";

const DEFAULTS = {
  adapterType: "wordpressWooCommerce",
  domain: "http://localhost:8080",
  homepage: "home",
  mode: "development",
  outputDir: "dist",
  siteName: "WPSC Site",
  theme: "commerce",
  wordpressUrl: "https://example.com"
};

function quote(value) {
  return JSON.stringify(value);
}

function normalizeUrl(value, fallback) {
  const candidate = String(value || fallback).trim();

  try {
    return new URL(candidate).toString().replace(/\/$/, "");
  } catch {
    return candidate;
  }
}

function createProjectConfig(options) {
  return {
    adapter: {
      type: options.adapterType,
      woocommerce: {
        baseUrl: options.woocommerceUrl,
        consumerKey: "process.env.WPSC_WOO_CONSUMER_KEY",
        consumerSecret: "process.env.WPSC_WOO_CONSUMER_SECRET"
      },
      wordpress: {
        baseUrl: options.wordpressUrl
      }
    },
    homepage: options.homepage,
    name: options.siteName,
    outputDir: options.outputDir,
    site: {
      url: options.domain
    },
    theme: {
      assets: "./theme/assets",
      components: "./theme/components/index.js",
      layout: "./theme/layout.js",
      name: options.theme
    }
  };
}

function createEnvFile(options) {
  return `# Generated by WPSC installation wizard.
WPSC_SITE_URL=${options.domain}
WPSC_WP_URL=${options.wordpressUrl}
WPSC_WOO_URL=${options.woocommerceUrl}
WPSC_WOO_CONSUMER_KEY=change-me
WPSC_WOO_CONSUMER_SECRET=change-me
WPSC_RUNTIME_PORT=${options.runtimePort}
WPSC_SESSION_SECRET=change-me
WPSC_AUTH_BRIDGE_SECRET=change-me
WPSC_AUTH_ENDPOINT=/wp-json/wpsc/v1/auth/login
`;
}

function createProjectConfigFile(options) {
  return `const wordpressUrl = process.env.WPSC_WP_URL ?? ${quote(options.wordpressUrl)};
const woocommerceUrl = process.env.WPSC_WOO_URL ?? ${quote(options.woocommerceUrl)};
const siteUrl = process.env.WPSC_SITE_URL ?? ${quote(options.domain)};

export default {
  name: ${quote(options.siteName)},
  homepage: ${quote(options.homepage)},
  outputDir: ${quote(options.outputDir)},
  adapter: {
    type: ${quote(options.adapterType)},
    wordpress: {
      baseUrl: wordpressUrl
    },
    woocommerce: {
      baseUrl: woocommerceUrl,
      consumerKey: process.env.WPSC_WOO_CONSUMER_KEY,
      consumerSecret: process.env.WPSC_WOO_CONSUMER_SECRET
    }
  },
  theme: {
    name: ${quote(options.theme)},
    layout: "./theme/layout.js",
    components: "./theme/components/index.js",
    assets: "./theme/assets"
  },
  site: {
    url: siteUrl
  }
};
`;
}

function createRuntimeConfigFile(options) {
  return `export default {
  mode: ${quote(options.mode)},
  projectDir: process.cwd(),
  outputDir: ${quote(options.outputDir)},
  cacheDir: ".wpsc/cache",
  services: {},
  extensions: []
};
`;
}

function createFiles(options) {
  return [
    {
      contents: createEnvFile(options),
      path: ".env"
    },
    {
      contents: createProjectConfigFile(options),
      path: "wpsc.config.js"
    },
    {
      contents: createRuntimeConfigFile(options),
      path: "runtime.config.js"
    },
    {
      contents: "export default function renderPage({ content }) {\n  return String(content?.html || content?.content || \"\");\n}\n",
      path: "theme/layout.js"
    },
    {
      contents: "export default {};\n",
      path: "theme/components/index.js"
    }
  ];
}

export default function createInstallationConfigGenerator(options = {}) {
  const normalized = {
    adapterType: options.adapterType || DEFAULTS.adapterType,
    domain: normalizeUrl(options.domain, DEFAULTS.domain),
    homepage: options.homepage || DEFAULTS.homepage,
    mode: options.mode || DEFAULTS.mode,
    outputDir: options.outputDir || DEFAULTS.outputDir,
    projectDir: options.projectDir || process.cwd(),
    runtimePort: Number(options.runtimePort || 8787),
    siteName: options.siteName || DEFAULTS.siteName,
    theme: options.theme || DEFAULTS.theme,
    woocommerceUrl: normalizeUrl(options.woocommerceUrl || options.wordpressUrl, DEFAULTS.wordpressUrl),
    wordpressUrl: normalizeUrl(options.wordpressUrl, DEFAULTS.wordpressUrl)
  };

  const runtime = createRuntimeConfig({
    cacheDir: ".wpsc/cache",
    extensions: [],
    mode: normalized.mode,
    outputDir: normalized.outputDir,
    projectDir: normalized.projectDir,
    services: {}
  });
  const project = createProjectConfig(normalized);
  const warnings = [];

  if (!options.wordpressUrl) {
    warnings.push({
      code: "install.config.wordpress.placeholder",
      message: "WordPress URL uses the default placeholder.",
      fix: "Enter the real WordPress API URL before installation continues."
    });
  }

  if (!options.domain) {
    warnings.push({
      code: "install.config.domain.placeholder",
      message: "Domain uses the default local URL.",
      fix: "Enter the real site domain before production installation."
    });
  }

  return {
    config: {
      project,
      runtime: runtime.config
    },
    diagnostics: {
      errors: [...runtime.diagnostics.errors],
      warnings: [...runtime.diagnostics.warnings, ...warnings]
    },
    files: createFiles(normalized),
    ok: runtime.ok,
    options: normalized,
    version: INSTALLATION_CONFIG_GENERATOR_VERSION
  };
}
