import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  createOk,
  createWarning,
  summarizeValidationResults
} from "../validation/createValidationResult.js";

const DEFAULTS = {
  domain: "http://localhost:8080",
  outputDir: "./dist",
  siteName: "WPSC Site",
  theme: "commerce",
  wordpressUrl: "https://example.com"
};

export default async function createInstallConfiguration(projectDir, options = {}) {
  const absoluteProjectDir = path.resolve(projectDir);
  const installOptions = normalizeInstallOptions(options);
  const files = createInstallFiles(installOptions);
  const results = [];

  await mkdir(absoluteProjectDir, { recursive: true });

  for (const file of files) {
    const absolutePath = path.join(absoluteProjectDir, file.path);

    await mkdir(path.dirname(absolutePath), { recursive: true });
    await writeFile(absolutePath, file.contents, {
      encoding: "utf8",
      flag: installOptions.force ? "w" : "wx"
    });

    results.push(createOk(`Generated ${file.path}`, absolutePath, {
      category: "install",
      summary: `${file.path} was generated.`
    }));
  }

  if (installOptions.usesDefaultWordPressUrl) {
    results.push(createWarning("WordPress URL", installOptions.wordpressUrl, {
      category: "install",
      fix: "Run wpsc install with --wordpress-url or edit WPSC_WP_URL in .env.",
      summary: "The install wizard used a placeholder WordPress URL."
    }));
  }

  if (installOptions.usesDefaultDomain) {
    results.push(createWarning("Domain URL", installOptions.domain, {
      category: "install",
      fix: "Run wpsc install with --domain or edit WPSC_SITE_URL in .env.",
      summary: "The install wizard used a local development domain."
    }));
  }

  return {
    files: files.map((file) => path.join(absoluteProjectDir, file.path)),
    options: installOptions,
    projectDir: absoluteProjectDir,
    results,
    summary: summarizeValidationResults(results)
  };
}

function normalizeInstallOptions(options = {}) {
  const wordpressUrl = normalizeUrl(options.wordpressUrl, DEFAULTS.wordpressUrl, "wordpressUrl");
  const domain = normalizeUrl(options.domain, DEFAULTS.domain, "domain");

  return {
    domain,
    force: Boolean(options.force),
    outputDir: normalizeOutputDir(options.outputDir),
    siteName: normalizeText(options.siteName, DEFAULTS.siteName),
    theme: normalizeText(options.theme, DEFAULTS.theme),
    usesDefaultDomain: !options.domain,
    usesDefaultWordPressUrl: !options.wordpressUrl,
    woocommerceUrl: normalizeUrl(options.woocommerceUrl, wordpressUrl, "woocommerceUrl"),
    wordpressUrl
  };
}

function createInstallFiles(options) {
  return [
    {
      path: ".env",
      contents: createEnvFile(options)
    },
    {
      path: "wpsc.config.js",
      contents: createProjectConfigFile(options)
    },
    {
      path: "runtime.config.js",
      contents: createRuntimeConfigFile(options)
    },
    {
      path: "theme/layout.js",
      contents: createThemeLayoutFile()
    },
    {
      path: "theme/components/index.js",
      contents: "export default {};\n"
    },
    {
      path: "theme/assets/.gitkeep",
      contents: ""
    },
    {
      path: "public/.gitkeep",
      contents: ""
    }
  ];
}

function createEnvFile(options) {
  return `# Generated by wpsc install.
WPSC_SITE_URL=${options.domain}
WPSC_WP_URL=${options.wordpressUrl}
WPSC_WOO_URL=${options.woocommerceUrl}
WPSC_WOO_CONSUMER_KEY=change-me
WPSC_WOO_CONSUMER_SECRET=change-me
WPSC_RUNTIME_PORT=8787
WPSC_SESSION_SECRET=change-me
WPSC_AUTH_BRIDGE_SECRET=change-me
WPSC_AUTH_ENDPOINT=/wp-json/wpsc/v1/auth/login
`;
}

function createProjectConfigFile(options) {
  return `const wordpressUrl = process.env.WPSC_WP_URL ?? ${quote(options.wordpressUrl)};
const woocommerceUrl = process.env.WPSC_WOO_URL ?? wordpressUrl;
const siteUrl = process.env.WPSC_SITE_URL ?? ${quote(options.domain)};

export default {
  name: ${quote(options.siteName)},
  homepage: "home",
  outputDir: ${quote(options.outputDir)},
  adapter: {
    type: "wordpressWooCommerce",
    wordpress: {
      baseUrl: wordpressUrl
    },
    woocommerce: {
      baseUrl: woocommerceUrl,
      consumerKey: process.env.WPSC_WOO_CONSUMER_KEY,
      consumerSecret: process.env.WPSC_WOO_CONSUMER_SECRET
    }
  },
  theme: {
    name: ${quote(options.theme)},
    layout: "./theme/layout.js",
    components: "./theme/components/index.js",
    assets: "./theme/assets"
  },
  site: {
    url: siteUrl
  }
};
`;
}

function createRuntimeConfigFile(options) {
  return `const wordpressUrl = process.env.WPSC_WP_URL ?? ${quote(options.wordpressUrl)};

export default {
  runtime: {
    port: Number(process.env.WPSC_RUNTIME_PORT ?? 8787),
    wordpressUrl,
    authEndpoint: process.env.WPSC_AUTH_ENDPOINT ?? "/wp-json/wpsc/v1/auth/login",
    session: {
      cookieName: "wpsc_session",
      secret: process.env.WPSC_SESSION_SECRET ?? "change-me",
      secure: process.env.NODE_ENV === "production"
    }
  }
};
`;
}

function createThemeLayoutFile() {
  return `export default function layout(page = {}) {
  const title = page.title ?? "WPSC";
  const body = page.html ?? page.content ?? "";

  return \`<!doctype html>
<html lang="vi">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>\${title}</title>
  </head>
  <body>
    <main data-wpsc-route="\${page.slug ?? ""}">
      <h1>\${title}</h1>
      \${body}
    </main>
  </body>
</html>\`;
}
`;
}

function normalizeOutputDir(value) {
  const outputDir = normalizeText(value, DEFAULTS.outputDir);

  if (path.isAbsolute(outputDir)) {
    throw new Error("Install option outputDir must be relative to the project directory.");
  }

  return outputDir;
}

function normalizeText(value, fallback) {
  const text = String(value ?? "").trim();

  return text || fallback;
}

function normalizeUrl(value, fallback, optionName) {
  const text = normalizeText(value, fallback);

  try {
    const url = new URL(text);

    if (url.protocol !== "http:" && url.protocol !== "https:") {
      throw new Error("Unsupported protocol");
    }

    return url.toString().replace(/\/$/, "");
  } catch {
    throw new Error(`Install option ${optionName} must be a valid http:// or https:// URL.`);
  }
}

function quote(value) {
  return JSON.stringify(value);
}
